# Generated by Django 4.0.3 on 2024-02-08 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales_rest', '0002_rename_sales_person_recordofsale_salesperson'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recordofsale',
            name='salesperson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='salesperson', to='sales_rest.salesperson'),
        ),
    ]
