# Generated by Django 4.0.3 on 2024-02-07 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0003_alter_appointment_technician'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='status',
            options={'ordering': ('name',), 'verbose_name_plural': 'statuses'},
        ),
        migrations.AddField(
            model_name='appointment',
            name='vip',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='technician',
            name='employee_id',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
