# Generated by Django 4.0.3 on 2024-02-08 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0005_alter_appointment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technician',
            name='employee_id',
            field=models.IntegerField(max_length=50),
        ),
    ]
